#!/usr/bin/env bash
# Regenerates every list's index.html from the root index.html.
#
# The page shell is identical for everyone, so it is written once at the repo
# root and copied into each list folder with its asset paths rewritten and its
# title swapped for that list's own. Edit index.html at the root, never a
# generated one. deploy.sh runs this for you.
set -euo pipefail

cd "$(dirname "$0")"

SHELL_FILE="index.html"
count=0

# The title as it is written in a list's products.js, e.g. Jared's Dress Code.
read_title() {
  sed -n 's/^[[:space:]]*title:[[:space:]]*"\(.*\)",[[:space:]]*$/\1/p' "$1" | head -1
}

# A title is arbitrary text going into both HTML and a sed replacement, so it
# is escaped for each in turn.
escape_title() {
  printf '%s' "$1" |
    sed -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g' |
    sed -e 's/[\\&|]/\\&/g'
}

for manifest in */products.js; do
  [ -e "$manifest" ] || continue

  dir="$(dirname "$manifest")"
  target="$dir/index.html"
  title="$(read_title "$manifest")"

  if [ -z "$title" ]; then
    echo "No title found in $manifest, keeping the shell's title." >&2
    title_rule="s|<title>|<title>|"
  else
    title_rule="s|<title>.*</title>|<title>$(escape_title "$title")</title>|"
  fi

  {
    echo "<!-- Generated by sync-lists.sh from the root index.html."
    echo "     Do not edit this file. Edit index.html at the repo root and"
    echo "     run ./sync-lists.sh. -->"
    # products.js is left alone on purpose: relative to this folder it already
    # resolves to the list's own products. The closing quote is not matched, so
    # these keep working once deploy.sh appends a ?v= cache stamp.
    sed -e 's|href="styles.css|href="../styles.css|' \
      -e 's|src="app.js|src="../app.js|' \
      -e "$title_rule" \
      "$SHELL_FILE"
  } >"$target"

  count=$((count + 1))
  echo "synced $target  ($title)"
done

echo "$count list shell(s) now match $SHELL_FILE"
